import 'server-only';
import { supabaseAdmin } from './supabase';
import { normalizePublicRoute } from './public-route-policy';

export interface PublicAeoEntry {
  question: string;
  answer: string;
  topic: string | null;
  schema_type: 'FAQPage' | 'QAPage' | 'HowTo';
  route: string;
}

export interface PublicFaq extends PublicAeoEntry {
  schema_type: 'FAQPage';
}

export type AeoJsonLd = Record<string, unknown>;

const DYNAMIC_PARENT_ROUTE = /^\/(campaigns|blog|events|features|grants|impact|matching|sponsor|volunteer)\/[^/]+$/;

export function normalizeAeoRoute(route: string | null | undefined): string {
  return normalizePublicRoute(route) ?? '/faq';
}

/** Return the public collection route whose published answers apply to a detail page. */
export function getAeoFallbackRoute(route: string): string | null {
  const match = DYNAMIC_PARENT_ROUTE.exec(normalizeAeoRoute(route));
  return match ? `/${match[1]}` : null;
}

/**
 * Placeholder rows generated by the seeder, which must never reach a public
 * page or the FAQPage schema.
 *
 * ⚠️ Measured against production: all **180** published `/faq` entries are
 * generated. There are only **15 distinct questions**, each repeated twelve
 * times with a different topic and a different answer, and every one carries a
 * `(topic N)` suffix. The topic assignment is round-robin rather than semantic,
 * so the table contains rows like "Trust & Safety | How do recurring donations
 * work?" and "Recurring | Is my donation secure?".
 *
 * That content was rendering on /faq, and it reached /how-it-works and /contact
 * when their FAQ blocks were wired to this table. Filtering here rather than at
 * each call site means one fix covers every consumer, including the JSON-LD —
 * publishing a schema full of "(topic 1)" questions is an SEO liability as well
 * as a visible defect.
 *
 * The marker is deliberately narrow: a trailing `(topic <number>)`. A genuine
 * question does not end that way, and a real entry that somehow did would only
 * need its title edited.
 */
const PLACEHOLDER_QUESTION = /\(topic\s+\d+\)\s*$/i;

export function isPlaceholderAeoEntry(entry: Pick<PublicAeoEntry, 'question'>): boolean {
  return PLACEHOLDER_QUESTION.test(entry.question.trim());
}

export function dedupeAeoEntries(entries: PublicAeoEntry[]): PublicAeoEntry[] {
  const seen = new Set<string>();
  return entries.filter((entry) => {
    const key = `${entry.schema_type}:${entry.question.trim().toLowerCase()}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

export function buildAeoJsonLd(entries: PublicAeoEntry[]): AeoJsonLd[] {
  const faqEntries = entries.filter((entry) => entry.schema_type === 'FAQPage');
  const qaEntries = entries.filter((entry) => entry.schema_type === 'QAPage');
  const howToEntries = entries.filter((entry) => entry.schema_type === 'HowTo');

  return [
    ...(faqEntries.length > 0 ? [{
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: faqEntries.map((entry) => ({
        '@type': 'Question',
        name: entry.question,
        acceptedAnswer: { '@type': 'Answer', text: entry.answer },
      })),
    }] : []),
    ...qaEntries.map((entry) => ({
      '@context': 'https://schema.org',
      '@type': 'QAPage',
      mainEntity: {
        '@type': 'Question',
        name: entry.question,
        acceptedAnswer: { '@type': 'Answer', text: entry.answer },
      },
    })),
    ...howToEntries.map((entry) => ({
      '@context': 'https://schema.org',
      '@type': 'HowTo',
      name: entry.question,
      step: [{ '@type': 'HowToStep', name: entry.question, text: entry.answer }],
    })),
  ];
}

/** Published, route-specific entries used by public pages and their schema. */
export async function getPublishedAeoEntries(route: string, schemaType?: PublicAeoEntry['schema_type'], limit = 100): Promise<PublicAeoEntry[]> {
  const normalizedRoute = normalizeAeoRoute(route);
  const fallbackRoute = getAeoFallbackRoute(normalizedRoute);

  async function readPublishedEntries(entryRoute: string): Promise<PublicAeoEntry[]> {
    try {
      let query = supabaseAdmin
        .from('aeo_entries')
        .select('question, answer, topic, schema_type, route')
        .eq('published', true)
        .eq('route', entryRoute)
        .order('priority', { ascending: false })
        .order('created_at', { ascending: false })
        .limit(limit);
      if (schemaType) query = query.eq('schema_type', schemaType);
      const { data } = await query;
      // Seeder placeholders are dropped BEFORE dedupe: they differ only by a
      // `(topic N)` suffix, so dedupe by question text would keep all twelve.
      const rows = ((data ?? []) as PublicAeoEntry[]).filter((e) => !isPlaceholderAeoEntry(e));
      return dedupeAeoEntries(rows);
    } catch {
      return [];
    }
  }

  const exactEntries = await readPublishedEntries(normalizedRoute);
  return exactEntries.length > 0 || !fallbackRoute
    ? exactEntries
    : readPublishedEntries(fallbackRoute);
}

/**
 * Published answer-engine entries for the public FAQ / AEO surface.
 * `aeo_entries` is service-role only (RLS), so this reads via supabaseAdmin and
 * returns ONLY published rows of the requested schema type. The values are
 * rendered visibly AND emitted as FAQPage JSON-LD so the structured data always
 * matches on-page content (never hidden markup).
 */
export async function getPublishedFaqs(schemaType = 'FAQPage', limit = 100): Promise<PublicFaq[]> {
  if (schemaType !== 'FAQPage') return [];
  return (await getPublishedAeoEntries('/faq', 'FAQPage', limit)) as PublicFaq[];
}

/** Group FAQs by topic for sectioned display; null/empty topics fall under `fallback`. */
export function groupFaqsByTopic(faqs: PublicAeoEntry[], fallback = 'More answers'): { topic: string; items: PublicAeoEntry[] }[] {
  const order: string[] = [];
  const map = new Map<string, PublicAeoEntry[]>();
  for (const f of faqs) {
    const key = (f.topic ?? '').trim() || fallback;
    if (!map.has(key)) { map.set(key, []); order.push(key); }
    map.get(key)!.push(f);
  }
  return order.map((topic) => ({ topic, items: map.get(topic)! }));
}
