-- Seed 50 fake sponsors rows (idempotent — skips if any rows exist)
do $$
begin
  if (select count(*) from public.sponsors) > 0 then
    return;
  end if;

  insert into public.sponsors (name, logo_url, website, active, sort_order) values
    ('Google.org',     'https://logo.clearbit.com/google.org',           'https://google.org',           true,  1),
    ('Salesforce',     'https://logo.clearbit.com/salesforce.com',        'https://salesforce.com',        true,  2),
    ('Microsoft',      'https://logo.clearbit.com/microsoft.com',         'https://microsoft.com',         true,  3),
    ('Apple',          'https://logo.clearbit.com/apple.com',             'https://apple.com',             true,  4),
    ('Amazon',         'https://logo.clearbit.com/amazon.com',            'https://amazon.com',            true,  5),
    ('Meta',           'https://logo.clearbit.com/meta.com',              'https://meta.com',              true,  6),
    ('Stripe',         'https://logo.clearbit.com/stripe.com',            'https://stripe.com',            true,  7),
    ('Shopify',        'https://logo.clearbit.com/shopify.com',           'https://shopify.com',           true,  8),
    ('Airbnb',         'https://logo.clearbit.com/airbnb.com',            'https://airbnb.com',            true,  9),
    ('PayPal',         'https://logo.clearbit.com/paypal.com',            'https://paypal.com',            true,  10),
    ('Visa',           'https://logo.clearbit.com/visa.com',              'https://visa.com',              true,  11),
    ('Mastercard',     'https://logo.clearbit.com/mastercard.com',        'https://mastercard.com',        true,  12),
    ('Twilio',         'https://logo.clearbit.com/twilio.com',            'https://twilio.com',            true,  13),
    ('HubSpot',        'https://logo.clearbit.com/hubspot.com',           'https://hubspot.com',           true,  14),
    ('Mailchimp',      'https://logo.clearbit.com/mailchimp.com',         'https://mailchimp.com',         true,  15),
    ('Slack',          'https://logo.clearbit.com/slack.com',             'https://slack.com',             true,  16),
    ('Zoom',           'https://logo.clearbit.com/zoom.us',               'https://zoom.us',               true,  17),
    ('Dropbox',        'https://logo.clearbit.com/dropbox.com',           'https://dropbox.com',           true,  18),
    ('Atlassian',      'https://logo.clearbit.com/atlassian.com',         'https://atlassian.com',         true,  19),
    ('Notion',         'https://logo.clearbit.com/notion.so',             'https://notion.so',             true,  20),
    ('Figma',          'https://logo.clearbit.com/figma.com',             'https://figma.com',             false, 21),
    ('GitHub',         'https://logo.clearbit.com/github.com',            'https://github.com',            true,  22),
    ('Vercel',         'https://logo.clearbit.com/vercel.com',            'https://vercel.com',            true,  23),
    ('Supabase',       'https://logo.clearbit.com/supabase.com',          'https://supabase.com',          true,  24),
    ('Cloudflare',     'https://logo.clearbit.com/cloudflare.com',        'https://cloudflare.com',        true,  25),
    ('Intercom',       'https://logo.clearbit.com/intercom.com',          'https://intercom.com',          false, 26),
    ('Zendesk',        'https://logo.clearbit.com/zendesk.com',           'https://zendesk.com',           true,  27),
    ('DocuSign',       'https://logo.clearbit.com/docusign.com',          'https://docusign.com',          true,  28),
    ('Adobe',          'https://logo.clearbit.com/adobe.com',             'https://adobe.com',             true,  29),
    ('Canva',          'https://logo.clearbit.com/canva.com',             'https://canva.com',             true,  30),
    ('Typeform',       'https://logo.clearbit.com/typeform.com',          'https://typeform.com',          false, 31),
    ('Airtable',       'https://logo.clearbit.com/airtable.com',          'https://airtable.com',          true,  32),
    ('Monday.com',     'https://logo.clearbit.com/monday.com',            'https://monday.com',            true,  33),
    ('Asana',          'https://logo.clearbit.com/asana.com',             'https://asana.com',             false, 34),
    ('Linear',         'https://logo.clearbit.com/linear.app',            'https://linear.app',            true,  35),
    ('Loom',           'https://logo.clearbit.com/loom.com',              'https://loom.com',              true,  36),
    ('Calendly',       'https://logo.clearbit.com/calendly.com',          'https://calendly.com',          true,  37),
    ('Webflow',        'https://logo.clearbit.com/webflow.com',           'https://webflow.com',           false, 38),
    ('Squarespace',    'https://logo.clearbit.com/squarespace.com',       'https://squarespace.com',       true,  39),
    ('Wix',            'https://logo.clearbit.com/wix.com',               'https://wix.com',               false, 40),
    ('Klaviyo',        'https://logo.clearbit.com/klaviyo.com',           'https://klaviyo.com',           true,  41),
    ('Brex',           'https://logo.clearbit.com/brex.com',              'https://brex.com',              true,  42),
    ('Rippling',       'https://logo.clearbit.com/rippling.com',          'https://rippling.com',          false, 43),
    ('Gusto',          'https://logo.clearbit.com/gusto.com',             'https://gusto.com',             true,  44),
    ('QuickBooks',     'https://logo.clearbit.com/quickbooks.intuit.com', 'https://quickbooks.intuit.com', false, 45),
    ('Plaid',          'https://logo.clearbit.com/plaid.com',             'https://plaid.com',             true,  46),
    ('Segment',        'https://logo.clearbit.com/segment.com',           'https://segment.com',           false, 47),
    ('Mixpanel',       'https://logo.clearbit.com/mixpanel.com',          'https://mixpanel.com',          true,  48),
    ('Amplitude',      'https://logo.clearbit.com/amplitude.com',         'https://amplitude.com',         false, 49),
    ('Datadog',        'https://logo.clearbit.com/datadoghq.com',         'https://datadoghq.com',         true,  50);
end $$;
